services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.vercel
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - arcade

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.vercel
    ports:
      - "8000:80"
    networks:
      - arcade

networks:
  arcade:
    driver: bridge
